/**
 * Export utilities — generate professional formatted outputs
 */

export function exportAsJSON(data, filename = 'analysis.json') {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  triggerDownload(blob, filename);
}

export function exportAsMarkdown(content, filename = 'analysis.md') {
  const blob = new Blob([content], { type: 'text/markdown' });
  triggerDownload(blob, filename);
}

export function exportAsPDF() {
  window.print();
}

export function copyToClipboard(text) {
  return navigator.clipboard.writeText(text);
}

/**
 * Build a professional Markdown report from analysis data
 */
export function buildMarkdownReport({ metadata, sections, languages, techStack }) {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const repoUrl = metadata?.fullName ? `https://github.com/${metadata.fullName}` : '';

  let md = `# Repository Intelligence Report: ${metadata?.name || 'Unknown Repository'}
  
> Generated by RepoLens AI · ${now}
> Repository: [${repoUrl}](${repoUrl})

---

## Repository Overview

| Field | Value |
|-------|-------|
| **Repository** | ${metadata?.fullName || '—'} |
| **Description** | ${metadata?.description || 'No description'} |
| **Owner** | ${metadata?.owner?.login || '—'} |
| **Stars** | ${(metadata?.stars || 0).toLocaleString()} |
| **Forks** | ${(metadata?.forks || 0).toLocaleString()} |
| **Open Issues** | ${(metadata?.openIssues || 0).toLocaleString()} |
| **License** | ${metadata?.license || 'None'} |
| **Default Branch** | ${metadata?.defaultBranch || 'main'} |
| **Created** | ${metadata?.createdAt ? new Date(metadata.createdAt).toLocaleDateString() : '—'} |
| **Last Updated** | ${metadata?.updatedAt ? new Date(metadata.updatedAt).toLocaleDateString() : '—'} |

`;

  if (languages && Object.keys(languages).length > 0) {
    const total = Object.values(languages).reduce((a, b) => a + b, 0);
    md += `## Languages\n\n`;
    Object.entries(languages)
      .sort(([, a], [, b]) => b - a)
      .forEach(([lang, bytes]) => {
        const pct = ((bytes / total) * 100).toFixed(1);
        md += `- **${lang}**: ${pct}%\n`;
      });
    md += '\n';
  }

  if (techStack?.length > 0) {
    md += `## Tech Stack\n\n${techStack.map(t => `- ${t}`).join('\n')}\n\n`;
  }

  // Health Score
  if (sections?.healthScore) {
    const s = sections.healthScore;
    md += `## Health Score\n\n`;
    md += `| Dimension | Score |\n|-----------|-------|\n`;
    const dims = ['overall', 'architecture', 'maintainability', 'documentation', 'security', 'organization'];
    dims.forEach(d => {
      if (s[d] !== undefined) {
        const label = d.charAt(0).toUpperCase() + d.slice(1);
        md += `| ${label} | ${s[d]}/100 |\n`;
      }
    });
    md += '\n';
  }

  const textSections = [
    { key: 'executiveSummary',          title: 'Executive Summary'         },
    { key: 'architectureAnalysis',      title: 'Architecture Analysis'     },
    { key: 'engineeringInsightsReport', title: 'Engineering Insights'      },
    { key: 'finalRecommendation',       title: 'Final Recommendation'      },
  ];

  textSections.forEach(({ key, title }) => {
    if (sections?.[key] && typeof sections[key] === 'string' && sections[key].trim()) {
      md += `## ${title}\n\n${sections[key].trim()}\n\n`;
    }
  });

  // Engineering Insights
  if (sections?.engineeringInsights) {
    const ei = sections.engineeringInsights;
    md += `## Engineering Insights\n\n`;
    if (ei.strengths?.length) {
      md += `### Strengths\n${ei.strengths.map(s => `- ${s}`).join('\n')}\n\n`;
    }
    if (ei.weaknesses?.length) {
      md += `### Weaknesses\n${ei.weaknesses.map(w => `- ${w}`).join('\n')}\n\n`;
    }
    const insightKeys = ['architectureQuality', 'maintainability', 'codeOrganization', 'testingCoverage', 'documentationQuality', 'developerExperience', 'scalability'];
    const labels = { architectureQuality: 'Architecture Quality', maintainability: 'Maintainability', codeOrganization: 'Code Organization', testingCoverage: 'Testing Coverage', documentationQuality: 'Documentation Quality', developerExperience: 'Developer Experience', scalability: 'Scalability' };
    md += `### Quality Dimensions\n\n| Dimension | Score | Assessment |\n|-----------|-------|------------|\n`;
    insightKeys.forEach(k => {
      if (ei[k]) {
        md += `| ${labels[k]} | ${ei[k].score}/100 | ${ei[k].explanation || ''} |\n`;
      }
    });
    md += '\n';
  }

  // Improvement Roadmap
  if (sections?.structuredImprovements) {
    const si = sections.structuredImprovements;
    md += `## Improvement Roadmap\n\n`;
    ['high', 'medium', 'low'].forEach(priority => {
      const items = si[priority];
      if (!items?.length) return;
      md += `### ${priority.charAt(0).toUpperCase() + priority.slice(1)} Priority\n\n`;
      items.forEach((item, i) => {
        md += `#### ${i + 1}. ${item.title}\n`;
        md += `- **Category**: ${item.category || '—'}\n`;
        md += `- **Effort**: ${item.effort || '—'} · **Impact**: ${item.impact || '—'}\n`;
        if (item.problem) md += `- **Problem**: ${item.problem}\n`;
        if (item.whyItMatters) md += `- **Why It Matters**: ${item.whyItMatters}\n`;
        if (item.evidence) md += `- **Evidence**: \`${item.evidence}\`\n`;
        if (item.implementation) md += `- **Implementation**: ${item.implementation}\n`;
        md += '\n';
      });
    });
  } else if (sections?.roadmap) {
    md += `## Improvement Roadmap\n\n${sections.roadmap}\n\n`;
  }

  md += `---\n*Report generated by [RepoLens AI](https://github.com) · ${now}*\n`;

  return md;
}

/**
 * Build complete JSON export
 */
export function buildJSONExport({ metadata, sections, languages, techStack, dependencies, security }) {
  return {
    generatedAt: new Date().toISOString(),
    generator: 'RepoLens AI',
    repository: {
      name: metadata?.name,
      fullName: metadata?.fullName,
      description: metadata?.description,
      url: metadata?.fullName ? `https://github.com/${metadata.fullName}` : null,
      owner: metadata?.owner,
      stars: metadata?.stars,
      forks: metadata?.forks,
      openIssues: metadata?.openIssues,
      license: metadata?.license,
      defaultBranch: metadata?.defaultBranch,
      createdAt: metadata?.createdAt,
      updatedAt: metadata?.updatedAt,
      pushedAt: metadata?.pushedAt,
      topics: metadata?.topics,
      size: metadata?.size,
    },
    languages,
    techStack,
    healthScore: sections?.healthScore,
    analysis: {
      summary: sections?.summary,
      repositoryPurpose: sections?.repositoryPurpose,
      architectureAnalysis: sections?.architectureAnalysis,
      engineeringDecisions: sections?.engineeringDecisions,
      productionReadiness: sections?.productionReadiness,
      maintainabilityAnalysis: sections?.maintainabilityAnalysis,
      documentationReview: sections?.documentationReview,
      scalabilityAssessment: sections?.scalabilityAssessment,
      testingAssessment: sections?.testingAssessment,
      contributionReadiness: sections?.contributionReadiness,
    },
    engineeringInsights: sections?.engineeringInsights,
    security: {
      observations: sections?.securityObservations || [],
      staticScan: security || [],
    },
    improvements: sections?.structuredImprovements || null,
    decision: sections?.decision || null,
    learningGuide: sections?.learningGuide || null,
  };
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
